# Generated by Django 4.2.5 on 2024-01-09 19:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='News_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='News_title', unique=True),
        ),
    ]
